### ISSUE TITLE
Table component sorts and rerender on onmouseover and onmouseout

### ISSUE THREAD

**Issue by AndreeWille** [sumup-oss/circuit-ui#1291]
## Describe the bug
On a sortable column when you put the mouse over or away from the header of the column that is sortable then the table gets sorted and rerendered. Which means that when a user clicks on a header with a the property sortable = true and afterwards moves the mouse away from the header then the table gets sorted 3 times. First time on onMouseOver, 2nd time on onClick and 3rd time on onMouseOut.

## Steps to reproduce

1. Add the prop sortable = true to a table header (dont fort get to add a sortLabel as well)
2. Either add a custom sort function with a console.log or start the profiler from the react dev tools.
3. Click on the sortable header and move the mouse out of the header.
4. Either you see 3 console.log statements in the console or 3 rerender of the table component in react dev tools.

## Expected behavior

Table will only be sorted once when a user clicks on the table header.

## Specifications

* Version: 4.5.1
* Browser: Latest Firefox and Latest Chrome
* OS: Mac OS 12.0.1

**Comment by robinmetral** [comment]
Thanks for reporting @AndreeWille, I can reproduce easily using by logging `onSortBy` calls in our [custom sort story](http://localhost:6006/?path=/story/components-table--custom-sort).

## The issue

This is happening because we listen to `mouseenter` and `mouseleave` events on the table header ([source](https://github.com/sumup-oss/circuit-ui/blob/c7483f0bbc206b80c693e6b5f856464e012683f7/packages/circuit-ui/components/Table/components/TableHead/TableHead.tsx#L138-L147)) in order to highlight the entire column to be sorted when the header cell is hovered.

The mouse enter and leave events update the `sortHover` in the Table's local state, which triggers a component update and calls the sort function via `getSortedRows` ([source](https://github.com/sumup-oss/circuit-ui/blob/c7483f0bbc206b80c693e6b5f856464e012683f7/packages/circuit-ui/components/Table/Table.tsx#L325)).

## The solution(s)

One way we can solve this is by avoiding to call `getSortedRows` inside the render method and rather move the sorted rows into state. PR on the way!

Alternatively, we could also remove the logic to highlight the entire column when the header cell is hovered: I don't think that this behavior is a big usability improvement, and it definitely worsens the component's performance and maintainability (as illustrated by this very issue), not to mention that it breaks the [comparable experience principle](https://inclusivedesignprinciples.org/#provide-comparable-experience) of inclusive design by not implementing the same behavior for keyboard users. If we were to remove these `mouseenter`/`mouseleave` handlers, only the header cell would be highlighted when it is hovered.

---

Side note: this is a legacy component and it will be entirely rewritten in an upcoming release. We will consider future bug fixes to the extent possible, but we can't prioritize them at this time. PRs are always welcome though 🙌

**Comment by robinmetral** [comment]
☝️ a PR with a suggested fix is here. [Try it on the deploy preview](https://oss-circuit-ui-git-fix-table-rerenders-sumup.vercel.app).

**Comment by robinmetral** [comment]
Closed by #1292, the fix is in `@sumup/circuit-ui@4.5.3`.

Thanks again for the report @AndreeWille!

**Comment by AndreeWille** [comment]
Thank you @robinmetral for fixing this so quickly!

**Comment by robinmetral** [comment]
The fix for the Table re-render had a bug, which was addressed in https://github.com/sumup-oss/circuit-ui/pull/1306.

However it looks like it reintroduced the re-render on Table header hover: reopening.

**Comment by AndreeWille** [comment]
I had a look into this and came to the conclusion that the issue is that hovering changes the state of the table which results in rerendering. 
From my understanding the state is only for higlighting the column, is this correct?

If yes, then i would be happy to prepare a pr where i remove the state change but instead add the html col tag according to the amount of headers and then dynamically set the background color on col when hovering. This should have the same effect.

Would this make sense to you?

**Comment by robinmetral** [comment]
> I had a look into this and came to the conclusion that the issue is that hovering over a table header changes the state of the table in order to store the column index, which results in rerendering the table.

Yes, exactly

> From my understanding the state is only for higlighting the column, is this correct?

I'm not sure, but we can try to remove it! A PR would be awesome, then we can make sure all tests pass and test the component in the Storybook. Let me know if you need help getting set up with the repo 🙂 ([Start here](https://circuit.sumup.com/?path=/docs/introduction-contributing-overview--page))
