### ISSUE TITLE
SideNavigation - secondary navigation first element with badge onClick bug

### ISSUE THREAD

**Issue by Marczerwinski** [sumup-oss/circuit-ui#1591]
## Describe the bug

While working on moving Items section from home secondary navigation to main navigation we found an issue in making the `badge` disapear  after click when **the element is the first element on the navigation list**. 

Element has the `badge` and clicking outside the element and re-clicking the element makes the badge disapear. Sometimes clicking outside the element makes the badge disapear (clicking on other list element). The problem doesn't appear when the element is not the first one on the list (then clicking on the element for the first time makes the badge disapear).

## Steps to reproduce

The bug is presented on the video  https://monosnap.com/file/4w1koLORAX5H34Oyt2iRqYmyKgUumI

## Expected behavior

The expected behavior would be to make the `badge` disapear while clicking outside the element.

## Specifications

* Version: 5.0.0
* Browser: 102.0.5005.61 (Official Build) (x86_64)
* OS: mac os

## Additional context

-

**Comment by robinmetral** [comment]
Thanks for the report @Marczerwinski. On desktop, when clicking a primary item, the first page under the item is loaded, but never actually clicked—so the badge stays. This wouldn't happen on mobile.

However I don't think that this can/should be addressed in Circuit UI—badge logic (i.e. when to show them and how to dismiss them) is handled is userland. In the dashboard, their logic is defined in the `NavigationService`. I imagine that the relevant service would need to check if there is a badge on the first secondary item, and dismiss that one if the parent primary item is clicked.

But more importantly, in terms of UX, if the first secondary item has a badge, I think it makes sense to move that badge to the primary item—because the first page will be loaded when the primary link is clicked. The caveat here would be the mobile behavior, of course.

Any other thought here? If there's any elegant way to handle this inside Circuit UI I'm happy to review a PR 🙂 cc also @connor-baer

**Comment by connor-baer** [comment]
> On desktop, when clicking a primary item, the first page under the item is loaded, but never actually clicked—so the badge stays

This is an edge case that we need to fix in the dashboard.

> But more importantly, in terms of UX, if the first secondary item has a badge, I think it makes sense to move that badge to the primary item

The primary item already gets a badge whenever any of its secondary items have a badge. We purposefully decided against badge on _only_ the primary navigation item because it might be confusing to users which secondary item actually contains new stuff.

**Comment by robinmetral** [comment]
> I looked at the code and apparently it is possible to add a badge directly to a primary item.

That's right, it's possible but we have logic preventing it at the moment. You're right, that was the reasoning behind it:

> We purposefully decided against badge on only the primary navigation item because it might be confusing to users which secondary item actually contains new stuff.

Anyways, no matter how we decide to address this, it sounds like it's useerland—closing 🙂
