### ISSUE TITLE
ImageInput component not accepting HEIC/HEIF formats

### ISSUE THREAD

**Issue by IBota** [sumup-oss/circuit-ui#1773]
## Describe the bug

The [ImageInput](https://circuit.sumup.com/?path=/docs/forms-imageinput--base) component does not accept HEIC/[HEIF](https://support.apple.com/en-us/HT207022) file formats in the **desktop** version.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Go to [ImageInput](https://circuit.sumup.com/?path=/docs/forms-imageinput--base) from a desktop machine
2. Open file selector
3. Try to upload a `.heic` file
4. File will appear greyed out/unselectable

## Expected behaviour

File should be allowed for upload

## Specifications

* Desktop machine
* Any `.heic` file

## Additional context

[Slack conversation](https://sumup.slack.com/archives/CURHLN94K/p1664440877488689)

**Comment by robinmetral** [comment]
To add to the above: here are HEIC and JPG sample images for testing (as .zip because GitHub doesn't support HEIC files 😅)

[heic-samples.zip](https://github.com/sumup-oss/circuit-ui/files/9675012/heic-samples.zip)

**Comment by robinmetral** [comment]
Hi again! I looked at this two weeks ago but forgot to report back in here—sorry!

I did some testing in [this CodeSandbox](https://codesandbox.io/s/heif-files-with-input-type-file-9whw8l), here are the results:

* **If your service supports HEIF images** (e.g. the uploaded image is an email attachment, the recipient uses macOS and can open it)
  * Use `accept="image/*,.heic"`. The attribute can be passed to the ImageInput component and will override the default `accept="image/*"` ([source](https://github.com/sumup-oss/circuit-ui/blob/be740a23953401e91e8d9dd4988de4e887f2d882/packages/circuit-ui/components/ImageInput/ImageInput.tsx#L439)). This will ensure that a HEIF image is recognised as valid by browser file pickers, including on Chrome.
  * ⚠️ The [Circuit UI ImageInput](https://circuit.sumup.com/?path=/story/forms-imageinput--base)'s image preview will not work, so users might think the file was not correctly uploaded. Worth exploring further with a designer. (Alternatively, there's a new ["FileInput" component on Figma](https://www.figma.com/file/2yHC0dK9pFEhLsMxk62XZY/Circuit-UI-Web?node-id=4921%3A27) (🔒 internal link), but it isn't yet implemented. Contributions welcome!)
  * Tell users what formats are supported (and any other limitations such as file size, dimensions, etc). You can use the ImageInput's `validationHint` prop for this ([example](https://circuit.sumup.com/?path=/story/forms-imageinput--base&args=validationHint:JPEG+and+HEIF+images+are+supported)).
* **If your service doesn't support HEIF images** (e.g. the uploaded image is a product image that will be displayed—without conversion—on an online store)
  * Use explicit MIME types for all supported formats, e.g. `accept="image/jpeg,image/png"`. This will have the benefit of Safari converting HEIF images to a supported format. The `accept` attribute can be passed to the ImageInput component and will override the default `accept="image/*"` ([source](https://github.com/sumup-oss/circuit-ui/blob/be740a23953401e91e8d9dd4988de4e887f2d882/packages/circuit-ui/components/ImageInput/ImageInput.tsx#L439)).
  * Tell users what formats are supported (and any other limitations such as file size, dimensions, etc). You can use the ImageInput's `validationHint` prop for this ([example](https://circuit.sumup.com/?path=/story/forms-imageinput--base&args=validationHint:JPEG+and+HEIF+images+are+supported)).

For more details on the testing and rationale for these recommendations, [refer to the CodeSandbox](https://codesandbox.io/s/heif-files-with-input-type-file-9whw8l) 🙂 

Based on the above, we wouldn't change anything in the Circuit UI `ImageInput` component, since what should be done is product-specific. Instead, I'm planning on documenting this in our Storybook docs.

@IBota does this answer your question? Let me know if you have any feedback or follow-ups about this 🙌

**Comment by robinmetral** [comment]
Closing this based on the above. Feel free to reopen if necessary 🙂
