### ISSUE TITLE
Improve validation messages

### ISSUE THREAD

**Issue by AlineLee** [sumup-oss/circuit-ui#577]
## Component to amend

Form fields: Input, Checkbox, Select, TextArea.

## Visual

![image](https://user-images.githubusercontent.com/1765898/80629549-5f934280-8a29-11ea-8269-a3391f1d14c0.png)

## Context

When the validation fails the message just goes away when the correct information is added. This compromises the user experience blocking other elements on screen.

Maybe if the red icon could just close the message and a red border was added the behavior be better.

**Comment by connor-baer** [comment]
Thanks for opening an issue @AlineLee! 

The behavior of the validation hint is not controlled by Circuit UI, it is left to the application to define it. The last time this behavior was discussed at SumUp was when we were developing Circuit UI. That's when we defined the current convention that's used across our apps. 

Using common sense, I agree that only showing the tooltip when the field is focused would be a more user-friendly approach. I don’t have a strong opinion on this, other than that it should be consistent and user-tested (our intuition could be wrong).

We can raise this topic again, ideally in the #design-system channel in Slack where the design team can join the discussion as well. Coincidentally, they are reviewing the input design at the moment. One idea is to show the validation hint upfront below the input field:

<img width="619" alt="Screenshot of a Circuit UI input with the help text visible below the input field" src="https://user-images.githubusercontent.com/11017722/81054446-29d9d800-8ec7-11ea-8898-a387e7510f60.png">

The help text would inform the user about the validation rules upfront, instead of screaming at them after they inadvertently mess up. On the other hand, it adds visual noise when there are many fields.

**Comment by connor-baer** [comment]
The validation message is now displayed _below_ the input as shown in the image in my previous comment.
