### ISSUE TITLE
[Beta] TabList fails to load in create-react-app because it uses component selectors

### ISSUE THREAD

**Issue by monken** [sumup-oss/circuit-ui#613]
## Describe the bug

Component selectors require which is not readily available for apps using create-react-app 

## Steps to reproduce

1. Load `<TabList>` component in a create-react-app

## Specifications

* Version: Beta-3

## Additional context

https://github.com/sumup-oss/circuit-ui/blob/beta/src/components/Tabs/components/TabList/TabList.js#L46 seems to be thee culprit.

There might be more instances across the code base where component selectors are used.

**Comment by connor-baer** [comment]
@monken Thank you for the report, this is very useful. I suspect it's because Circuit UI v2 is compiled with TypeScript instead of Babel and the [Emotion Babel plugin](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion) is no longer applied to the code. 

We'll fix this in Circuit UI, for the time being, I suggest to add the Babel plugin to your application and see if it works then.

**Comment by monken** [comment]
Hi @connor-baer, for any create-react-app application that would mean you'd have to eject which is strongly discouraged. Without rejecting, you cannot modify the babelrc file and add custom plugins.

**Comment by connor-baer** [comment]
That's not entirely true, you can use a custom Babel config without ejecting through [react-app-rewired](https://github.com/timarney/react-app-rewired). I'm not suggesting this as a permanent solution — we will fix this before the stable v2 release.

**Comment by connor-baer** [comment]
I'm going to close this issue since it has been resolved in the latest beta. @monken, please let us know if you encounter any other issues.
