### ISSUE TITLE
Drop babel-plugin-dev-expression depedency

### ISSUE THREAD

**Issue by monken** [sumup-oss/circuit-ui#680]
## Describe the bug

I ran into a deprecation warning for the `Input` component in a create-react-app application. They don't use the babel-plugin-dev-expression plugin so the browser spit out an exception about `__DEV__` not being defined. After some googling I found out that this can easily be fixed by defining `__DEV__` in your window scope. It seems like the only runtime-facing code where `__DEV__` is used is in the deprecate function. So I'd suggest to just replace it with `process.env.NODE_ENV !== 'production'`. This would fix this issue for users not using the babel plugin.

**Comment by connor-baer** [comment]
Hey @monken, thanks for the report and suggestion! Coincidentally, we ran into this at SumUp this week as well 🙈

I vaguely remember that there was a reason why we used `__DEV__` over `process.env.NODE_ENV` in v1, but I can't remember specifics (maybe it was because it was getting stripped during the build process so users never saw it?). Anyway, I've tested it again and now it's retained in the transpiled code. You're absolutely right that it's the better solution since it works out of the box and is better supported in the ecosystem. I've opened a PR to change the approach (#682).
