### ISSUE TITLE
Currency input - value being added to 0

### ISSUE THREAD

**Issue by Marczerwinski** [sumup-oss/circuit-ui#741]
## Describe the bug

While using currency input we (probably) found a bug connected to updating input value when previous value was `0`. When input value is equal to 0 (pic1) and I put focus on the input and start typing new value eg. `123` input value should be eqaul to `123` not `1.230` (pic2). This issue is problematic for starter merchants when they want to update costs of shippings.

## Steps to reproduce

Can be checked on circuit-ui storybook

1. Go to 'https://circuit.sumup.com/?path=/docs/forms-input-currencyinput--base'
2. Click on 'currency input'
3. Type 0
4. Click outside the input
5. Click on the input once again
6. Type 123
7. See that value is equal `1.230` instead of `123`

## Expected behavior

When input value is equal to `0` and we focus it and start typing new value, the `0` value should be deleted on keypress event.

## Specifications

* Version: v2
* Browser: chrome/safari/firefox
* OS: macos

## Additional context

pic(1)
![image](https://user-images.githubusercontent.com/18164156/101468591-ec996500-3943-11eb-805f-c7db2662dc90.png)

pic(2)
![image](https://user-images.githubusercontent.com/18164156/101468628-f753fa00-3943-11eb-98b9-903173ca8b43.png)

**Comment by connor-baer** [comment]
Thanks for filing a report, @Marczerwinski! What's the exact version of Circuit UI you're using?

**Comment by Marczerwinski** [comment]
> Thanks for filing a report, @Marczerwinski! What's the exact version of Circuit UI you're using?

hey @connor-baer, it was found on production, I see that on prod in dashboard `2.2.5` version is fired up

**Comment by felixjung** [comment]
Hey @Marczerwinski, have you tried version 2.3.0? It has a re-implementation of the currency input.

I've reproduced the behavior and re-read your description. I'm not sure what the expected behavior would be.

AFAIK, the initial value should be empty so that a user can see a placeholder. By entering a  `0`, we are telling the component to use a value of `0`. We could have also specified a value of `1`, in which case I would argue the behavior you are describing is expected.

You are right in that, in the context of currency values, `0` is special. For example, we shouldn't have a leading `0`. I would argue for the following expected behavior.

```js
describe("CurrencyInput", () => {
  describe("when focussing the input", () => {
    describe("when the current value is 0", () => {
      it.todo("should strip any leading 0 value on change")
      it.todo("should prepend to any trailing 0 value on change")
    })

    describe("when the current value is not 0", () => {
      it.todo("should prepend to any trailing values on change")
      it.todo("should append to any leading values on change")
    })
  })
})
```

The assumption here being that leading/trailing is relative to the cursor position at the onChange event.

What it comes down to is whether we, from a UX perspective, want to respect the `0` value or not. If someone typed wanted to enter `100` but somehow lost focus after a `0`, do we want to reset the state or do we want to allow them to continue. Both are fine approaches, but we would have to have a discussion about the expected behavior before labelling this as a bug.

What do you think?

**Comment by connor-baer** [comment]
In my opinion, the current behavior is the least confusing one. I fully agree with @felixjung's statement:

> AFAIK, the initial value should be empty so that a user can see a placeholder. By entering a 0, we are telling the component to use a value of 0. We could have also specified a value of 1, in which case I would argue the behavior you are describing is expected.

I did some experiments for the test cases that Felix outlined:

1. **Zero after cursor aka trailing zero:** As a user, I would be confused if the 0 was erased when I started typing.

![trailing zero](https://user-images.githubusercontent.com/11017722/101775705-27d89700-3af0-11eb-8cf0-ec1a817ce7f4.gif)

2. **Zero before cursor aka leading zero:** The 0 isn't trimmed immediately but when the field loses focus.

![leading zero](https://user-images.githubusercontent.com/11017722/101775399-b7317a80-3aef-11eb-9209-b9aafe060c9a.gif)

@Marczerwinski I recommend that you show the placeholder initially, as Felix suggested.
