### ISSUE TITLE
[RFC] Provide more extensibility to the Circuit components via a styling API 

### ISSUE THREAD

**Issue by justman00** [sumup-oss/circuit-ui#776]
Currently, the way to extend the styles or customize a Circuit-UI component, one needs to wrap it in the [emotion styled function](https://emotion.sh/docs/styled). While this is quite optimal when a component would undergo heavier `CSS` changes, it feels unnecessary when someone tries to edit just one property or add just a little bit more padding.

## Current way of doing things

```
const gridStyles = ({ theme }) => css`
  padding: ${theme.spacings.giga} 0;
`;

const StyledGrid = styled(Grid)(gridStyles);

function MyComponent() {
    return (
        <StyledGrid />
    )
}
```

## Proposed change

```
function MyComponent() {
    return (
        <Grid padding="spacings.giga 0" />
    )
}
```

## Additional information

The component could take style props, the same ones as one would do with inline styles. The props would get mapped to real styles applied directly to the component. However, a pattern would need to get established in order to support responsive design. Could be done via our already implemented way of `someStyleProp={{ base: 'colors.p500', kilo: 'colors.p700' }}` and so on.

## Benefits

Speed of development is something that comes to my mind. 
Easier to understand what styles are being applied to one or the other component.
Less code, at least on the end of the library user 😅 

## Chakra-UI
One library that does it extensively is [Chakra-UI](https://chakra-ui.com/) and the RFC is inspired heavily from their components styles API.

**Comment by connor-baer** [comment]
Hey @justman00, thank you so much for submitting this proposal! 

When designing the API for a component we need to balance consistency and flexibility. Circuit UI leans more towards consistency and tighter constraints. This has several benefits:

- a smaller API surface is less work to maintain
- a smaller API surface is easier to evolve over time
- the constraints enable us to make assumptions and optimize for specific use cases

Chakra UI is a generic UI library. Unlike Circuit UI, it's not made for a specific brand and a narrow set of use cases. That's why it leans more towards flexibility and customizability.

That being said, there are (other) ways to customize Circuit UI components. Are you aware of [Emotion's `css` prop](https://emotion.sh/docs/css-prop)? Here's your example rewritten using the `css` prop:

```tsx
function MyComponent() {
    return (
        <Grid css={(theme) => css`
  			padding: ${theme.spacings.giga} 0;
		`} />
    );
}

// Or alternatively:

const gridStyles = (theme) => css`
	padding: ${theme.spacings.giga} 0;
`;

function MyComponent() {
    return <Grid css={gridStyles} />;
}
```

There are plans to make this even easier for common use cases, such as adding spacing around a component. Have a look at the [spacing RFC](https://github.com/sumup-oss/circuit-ui/issues/534) and the `spacing` style mixin it proposes:

```tsx
function MyComponent() {
    return <Grid css={spacing({ bottom: 'giga' })} />;
}
```

What do you think of this approach? What other style mixins would you like to see?

**Comment by justman00** [comment]
Hey @connor-baer , thank you very much for the detailed answer. Indeed, the styles via the `css` prop could be a solution to the use case and is probably optimal for how we use circuit-ui internally. The issue was raised because I was feeling that there is always so much code to be written to add just a few more styles or adjust a little bit the spacing. Your points are definitely very valid, so thank you very much for that. 

The `spacing` mixin looks indeed quite promising, will definitely take a look at it.
