### ISSUE TITLE
Id within SVG generates accessibility issue

### ISSUE THREAD

**Issue by nicosommi** [sumup-oss/circuit-ui#874]
These [ids on SVG
](https://github.com/sumup-oss/icons/blob/e1fdcbd2ee4f98a19d1d30bb388c6be1917263b1/web/v1/flag_us_small.svg#L10) generate this kind of accessibility errors when displayed multiple times in a page:

![Screenshot 2021-01-28 at 14 32 43](https://user-images.githubusercontent.com/1702755/106145583-04d47600-6176-11eb-975b-4d8c6b73545b.png)

Can we just remove it?

**Comment by dmitri-suvorov-sumup** [comment]
Hey! We have an issue on the website because of duplicate clip-path IDs. On [this page](https://sumup.de/pos/) there are two dropdowns with flag icons. The first one shows all the icons correctly. The second one shows only the icons which don't have clip-path defined. 

![Screen Shot 2021-04-01 at 17 14 15](https://user-images.githubusercontent.com/53574544/113308052-7368b800-930e-11eb-8fa0-1f2005e89dd3.png)

I've tried to remove the clip-path in DevTools and the icon appears.
![Screen Shot 2021-04-01 at 17 21 58](https://user-images.githubusercontent.com/53574544/113308862-423cb780-930f-11eb-9c37-b21395b954c3.png)

Any ideas how to solve this?

**Comment by connor-baer** [comment]
Based on @nicosommi's closed PR (https://github.com/sumup-oss/icons/pull/45), I've removed the `clip-path` rule from any SVGs where it wasn't necessary: #883.
